import { Navigate } from 'react-router-dom';
import { useAdminAuth } from '@/hooks/useAdminAuth';

interface ProtectedAdminRouteProps {
  children: React.ReactNode;
}

export function ProtectedAdminRoute({ children }: ProtectedAdminRouteProps) {
  const { user, isLoading } = useAdminAuth();

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="animate-pulse text-primary">Loading...</div>
      </div>
    );
  }

  // Admin login flow: Allow access to /admin if Supabase Auth session exists
  // This uses Gmail + Password authentication via Supabase Auth
  if (!user) {
    return <Navigate to="/admin/login" replace />;
  }

  // Access token flow: Temporary / one-time access links generated by admin
  // Note: Access tokens are handled separately and not required for admin login
  // They are used for granting temporary access to users via links

  return <>{children}</>;
}
